name: mongo-sharding

services:
  mongo-config1:
    container_name: mongo-sharding-config1
    image: mongo:7
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "configRS",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    volumes:
      - mongo_config1_data:/data/db

  shard1:
    container_name: mongo-sharding-shard1
    image: mongo:7
    command:
      ["mongod", "--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27017"]
    volumes:
      - shard1_data:/data/db

  shard2:
    container_name: mongo-sharding-shard2
    image: mongo:7
    command:
      ["mongod", "--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27017"]
    volumes:
      - shard2_data:/data/db

  mongos:
    container_name: mongo-sharding-mongos
    image: mongo:7
    command:
      ["mongos", "--configdb", "configRS/mongo-config1:27017", "--bind_ip_all", "--port", "27017"]
    depends_on:
      - mongo-config1
      - shard1
      - shard2
    ports:
      - "27017:27017"

  pymongo_api:
    container_name: mongo-sharding-api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  mongo_config1_data:
  shard1_data:
  shard2_data:
