name: mongo-sharding-repl

services:
  # ==========================================
  # Config Server Replica Set (CSRS) - 3 nodes
  # ==========================================
  configSrv1:
    image: mongo:latest
    container_name: configSrv1
    restart: always
    command: ["--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017" # Доступ снаружи
    volumes:
      - config-data1:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv2:
    image: mongo:latest
    container_name: configSrv2
    restart: always
    command: ["--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27017"]
    # ports не нужны, общаемся внутри сети
    volumes:
      - config-data2:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv3:
    image: mongo:latest
    container_name: configSrv3
    restart: always
    command: ["--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27017"]
    volumes:
      - config-data3:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# ==========================================
  # Redis Cache
  # ==========================================
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      start_period: 10s

  # ==========================================
  # Shard 1 Replica Set - 3 nodes
  # ==========================================
  shard1-1:
    image: mongo:latest
    container_name: shard1-1
    restart: always
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - shard1-data1:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-2:
    image: mongo:latest
    container_name: shard1-2
    restart: always
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard1-data2:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-3:
    image: mongo:latest
    container_name: shard1-3
    restart: always
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard1-data3:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # ==========================================
  # Shard 2 Replica Set - 3 nodes
  # ==========================================
  shard2-1:
    image: mongo:latest
    container_name: shard2-1
    restart: always
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - shard2-data1:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-2:
    image: mongo:latest
    container_name: shard2-2
    restart: always
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27019"]
    volumes:
      - shard2-data2:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-3:
    image: mongo:latest
    container_name: shard2-3
    restart: always
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27019"]
    volumes:
      - shard2-data3:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # ==========================================
  # Mongos (Router)
  # ==========================================
  mongos:
    image: mongo:latest
    container_name: mongos
    restart: always
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
    command:
      - "mongos"
      # ВНИМАНИЕ: Здесь мы указываем весь Config Replica Set!
      - "--configdb"
      - "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017"
      - "--bind_ip_all"
      - "--port"
      - "27020"
    ports:
      - "27020:27020"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # ==========================================
  # Application
  # ==========================================
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: ../api_app
      dockerfile: Dockerfile
    depends_on:
      mongos:
        condition: service_healthy
      redis: 
        condition: service_healthy  
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    networks:
      - app-network

volumes:
  config-data1:
  config-data2:
  config-data3:
  shard1-data1:
  shard1-data2:
  shard1-data3:
  shard2-data1:
  shard2-data2:
  shard2-data3:
  redis-data:

networks:
  app-network:
    driver: bridge